# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d77e13be8606c29af999d3a0a9c118e72412786292e64a159d5fbb3e17d8b9d9b2e69017b2f19bb7ea13bfa848611c0ccb675f03c96a93167e9bc0643c55be

test:
  secret_key_base: d60b2ff67290deaeff389ff82bbe69f344cc0d3c5fdf67d1429b9e8745a9305971e9215e5d18875a1f3b1c0d7ab2bdcfd8fceb3aa0c59731552e63f16d0fbaac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
